/**
 * Audit pack — one PDF containing every signed record for a project in a
 * date range: cover page with summary, then each record (FLHA, QC,
 * environmental…) merged in chronological order.
 *
 * The WorkSafeBC moment: inspector shows up → office exports the pack →
 * done in a minute.
 */

import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { getFirestore } from 'firebase-admin/firestore';
import { getStorage } from 'firebase-admin/storage';
import { logger } from 'firebase-functions';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

interface AuditPackRequest {
  projectId: string;
  fromMs: number;
  toMs: number;
}

export const generateAuditPack = onCall<AuditPackRequest>(
  { memory: '1GiB', timeoutSeconds: 300 },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');
    const db = getFirestore();

    const caller = await db.collection('users').doc(request.auth.uid).get();
    const role = caller.data()?.role;
    if (role !== 'admin' && role !== 'manager') {
      throw new HttpsError('permission-denied', 'Office access only.');
    }

    const { projectId, fromMs, toMs } = request.data;
    if (!projectId || !fromMs || !toMs) {
      throw new HttpsError('invalid-argument', 'projectId, fromMs, toMs required.');
    }

    const bucket = getStorage().bucket();
    const projSnap = await db.collection('projects').doc(projectId).get();
    const projectName = projSnap.data()?.name ?? projectId;

    // Records in range, chronological
    const subs = await db.collection(`projects/${projectId}/submissions`)
      .where('submittedAt', '>=', new Date(fromMs))
      .where('submittedAt', '<=', new Date(toMs))
      .orderBy('submittedAt', 'asc')
      .get();

    // Attendance summary for the cover
    const att = await db.collection(`projects/${projectId}/attendance`)
      .where('clockInAt', '>=', new Date(fromMs))
      .where('clockInAt', '<=', new Date(toMs))
      .get();

    const fmt = (ms: number) => new Date(ms).toLocaleDateString('en-CA', { timeZone: 'America/Vancouver' });

    const out = await PDFDocument.create();
    const font = await out.embedFont(StandardFonts.Helvetica);
    const bold = await out.embedFont(StandardFonts.HelveticaBold);

    // ── Cover page ──
    const cover = out.addPage([612, 792]);
    let y = 720;
    const line = (text: string, size = 11, useBold = false, color = rgb(0.1, 0.1, 0.15)) => {
      cover.drawText(text, { x: 60, y, size, font: useBold ? bold : font, color });
      y -= size + 10;
    };
    line('SITE AUDIT PACK', 24, true, rgb(0.08, 0.2, 0.4));
    y -= 6;
    line(projectName, 16, true);
    line(`Period: ${fmt(fromMs)} to ${fmt(toMs)}`, 12);
    y -= 14;
    line(`Signed records included: ${subs.size}`, 12, true);
    line(`Attendance records in period: ${att.size}`, 12, true);
    y -= 14;
    line('Contents:', 12, true);

    const included: Array<{ path: string; label: string }> = [];
    for (const d of subs.docs) {
      const data = d.data();
      if (!data.pdfStoragePath) continue;
      const ms = data.submittedAt?.toMillis ? data.submittedAt.toMillis() : 0;
      const schemaSnap = await db.collection('forms').doc(String(data.schemaId ?? '')).get();
      const label = `${fmt(ms)} — ${schemaSnap.data()?.title ?? data.schemaId}`;
      included.push({ path: String(data.pdfStoragePath), label });
      if (y > 80) line(`  ${included.length}. ${label}`, 9);
    }
    y -= 10;
    cover.drawText(
      `Generated by Consite on ${new Date().toISOString()} · records completed and signed in-app with GPS + timestamp verification`,
      { x: 60, y: 40, size: 7, font, color: rgb(0.45, 0.45, 0.45) },
    );

    // ── Merge each record ──
    let merged = 0;
    for (const item of included) {
      try {
        const [bytes] = await bucket.file(item.path).download();
        const src = await PDFDocument.load(bytes);
        const pages = await out.copyPages(src, src.getPageIndices());
        pages.forEach((p) => out.addPage(p));
        merged += 1;
      } catch (err) {
        logger.warn(`Audit pack: could not merge ${item.path}`, err);
      }
    }

    const packBytes = Buffer.from(await out.save());
    const packPath = `projects/${projectId}/audit/audit-${fmt(fromMs)}-to-${fmt(toMs)}-${Date.now()}.pdf`;
    await bucket.file(packPath).save(packBytes, { contentType: 'application/pdf' });

    logger.info(`Audit pack for ${projectName}: ${merged}/${included.length} records merged, ${packBytes.length} bytes`);
    return { storagePath: packPath, records: merged, sizeBytes: packBytes.length };
  },
);
